### ISSUE TITLE
Demo code

### ISSUE THREAD

**Issue by peio72** [little-yellow-bean/vue-bs-modal#2]
Hello,

Great addon,

Could you publish the demo code ?

Thank you.

**Comment by little-yellow-bean** [comment]
Hi,

I have pushed the demo site code to this repo under the demo folder.

Thanks

**Comment by little-yellow-bean** [comment]
> Hello,
> 
> Great addon,
> 
> Could you publish the demo code ?
> 
> Thank you.

Hi,

I have pushed the demo site code to this repo under the demo folder.

Thanks

**Comment by peio72** [comment]
Thank you very much. It was pretty helpful for me to integrate the modal.
