### ISSUE TITLE
content: component and string problem

### ISSUE THREAD

**Issue by sy7777** [little-yellow-bean/vue-bs-modal#3]
![image](https://user-images.githubusercontent.com/37322972/209062393-f0ef376c-c34e-4ca7-97c9-ce0531d13c28.png)

Hi, 

When I pass a string to the content in ModalOption, there's no open modal but a background with shadow. Could you please help me with this? Many thanks

**Comment by little-yellow-bean** [comment]
> ![image](https://user-images.githubusercontent.com/37322972/209062393-f0ef376c-c34e-4ca7-97c9-ce0531d13c28.png)
> 
> Hi,
> 
> When I pass a string to the content in ModalOption, there's no open modal but a background with shadow. Could you please help me with this? Many thanks

can you please post your usage code? What string did you pass? You need to pass the component's registered name.

**Comment by sy7777** [comment]
I passed "Are you sure?", not a string of the component's registered name but a simple string. Because I wanna pass the data as a string to it. I tried to pass "Are you sure?"
![image](https://user-images.githubusercontent.com/37322972/209067599-fc88fadc-40ed-4c6b-b698-b01a37c9499f.png)

**Comment by little-yellow-bean** [comment]
You need to pass the component's registered name.

**Comment by sy7777** [comment]
What's the component mean? If just a string name needed?

**Comment by little-yellow-bean** [comment]
> What's the component mean? If just a string name needed?

https://vuejs.org/guide/components/registration.html#global-registration

**Comment by sy7777** [comment]
component不就是传字符串名字吗？那为啥还要写成component | string.
直接写component不行吗，我还以为component name 是component， string就是简单的字符串
